openapi: 3.0.0

info:
    title: Microsoft Entra ID - Delegated User Actions via Extension
    description: Microsoft Entra ID - Delegated User Actions via Extension
    version: "v1"

servers:
    - url: https://graph.microsoft.com/v1.0

paths:
    /users/{userPrincipalName}?$select=accountEnabled,authorizationInfo,businessPhones,city,companyName,country,createdDateTime,creationType,department,displayName,employeeId,givenName,id,imAddresses,jobTitle,lastPasswordChangeDateTime,mail,mailNickname,mobilePhone,officeLocation,securityIdentifier,state,streetAddress,surname,usageLocation,userPrincipalName,userType:
        get:
            operationId: Entra ID - Get User Details
            description: Get all the details about a user.
            summary: This skill will reset a password for a user.
            parameters:
                - in: path
                  name: userPrincipalName
                  schema:
                      type: string
                  required: true
                  description: Enter username for which you would like to get all the information.
            responses:
                "200":
                    description: OK
